# This file was generated by GoReleaser. DO NOT EDIT.
cask "clara" do
  name "clara"
  desc "Clara: Unified agent for personal automation (Go + Swift + Chrome)"
  homepage "https://github.com/brightpuddle/clara"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clara"
  binary "ClaraBridge"

  on_macos do
    on_intel do
      url "https://github.com/brightpuddle/clara/releases/download/v#{version}/clara_#{version}_darwin_amd64.tar.gz"
      sha256 "b6f545c78f40d94984601347f197d0cf2c0f173af158cca4c90c28daf86618a7"
    end
    on_arm do
      url "https://github.com/brightpuddle/clara/releases/download/v#{version}/clara_#{version}_darwin_arm64.tar.gz"
      sha256 "731c0124e2b26f6f6e607cb27085714b4a1e8cc42d9327cf96b624f06e411932"
    end
  end

  caveats do
    "To use the Chrome extension:"
    "1. Open Chrome -> chrome://extensions/"
    "2. Enable 'Developer mode'"
    "3. Click 'Load unpacked'"
    "4. Select: #{staged_path}/extension"
    ""
    "To start the Clara agent:"
    "1. Copy the launch agent to your user directory:"
    "   cp #{staged_path}/com.brightpuddle.clara.agent.plist ~/Library/LaunchAgents/"
    "2. Start it:"
    "   launchctl load ~/Library/LaunchAgents/com.brightpuddle.clara.agent.plist"
    ""
    "An example configuration is available at:"
    "#{staged_path}/config.yaml.example"
  end

  # No zap stanza required
end
