# This file was generated by GoReleaser. DO NOT EDIT.
cask "clara" do
  # Install ClaraBridge.app to the Caskroom so it can be executed
  # but not necessarily in /Applications
  artifact "ClaraBridge.app", target: "#{staged_path}/ClaraBridge.app"

  # Create a wrapper script for ClaraBridge to ensure it runs from the .app bundle
  # which is required for macOS UserNotifications.
  preflight do
    wrapper = "#{HOMEBREW_PREFIX}/bin/ClaraBridge"
    File.write(wrapper, <<~SH)
      #!/bin/bash
      exec "#{staged_path}/ClaraBridge.app/Contents/MacOS/ClaraBridge" "$@"
    SH
    FileUtils.chmod(0755, wrapper)
  end

  uninstall_preflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/ClaraBridge"
  end

  name "clara"
  desc "Clara: Unified agent for personal automation (Go + Swift + Chrome)"
  homepage "https://github.com/brightpuddle/clara"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clara"

  on_macos do
    on_intel do
      url "https://github.com/brightpuddle/clara/releases/download/v#{version}/clara_#{version}_darwin_amd64.tar.gz"
      sha256 "e6aef484c58641f17cb06636d612f9fe48ae76e02fe88871b0f056c479f3aa00"
    end
    on_arm do
      url "https://github.com/brightpuddle/clara/releases/download/v#{version}/clara_#{version}_darwin_arm64.tar.gz"
      sha256 "852de8fc54b1a8d157d3a04c319dceb0e4589153d737e279411291263dd99b2f"
    end
  end

  caveats do
    "To use the Chrome extension:"
    "1. Open Chrome -> chrome://extensions/"
    "2. Enable 'Developer mode'"
    "3. Click 'Load unpacked'"
    "4. Select: #{staged_path}/extension"
    ""
    "To start the Clara agent:"
    "1. Copy the launch agent to your user directory:"
    "   cp #{staged_path}/com.brightpuddle.clara.agent.plist ~/Library/LaunchAgents/"
    "2. Start it:"
    "   launchctl load ~/Library/LaunchAgents/com.brightpuddle.clara.agent.plist"
    ""
    "An example configuration is available at:"
    "#{staged_path}/config.yaml.example"
  end

  # No zap stanza required
end
