# This file was generated by GoReleaser. DO NOT EDIT.
cask "clara" do
  # Install ClaraBridge.app to the Caskroom so it can be executed
  # but not necessarily in /Applications
  artifact "ClaraBridge.app", target: "#{staged_path}/ClaraBridge.app"

  # Create a wrapper script for ClaraBridge to ensure it runs from the .app bundle
  # which is required for macOS UserNotifications.
  preflight do
    wrapper = "#{HOMEBREW_PREFIX}/bin/ClaraBridge"
    File.write(wrapper, <<~SH)
      #!/bin/bash
      exec "#{staged_path}/ClaraBridge.app/Contents/MacOS/ClaraBridge" "$@"
    SH
    FileUtils.chmod(0755, wrapper)
  end

  uninstall_preflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/ClaraBridge"
  end

  name "clara"
  desc "Clara: Unified agent for personal automation (Go + Swift + Chrome)"
  homepage "https://github.com/brightpuddle/clara"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clara"

  on_macos do
    on_intel do
      url "https://github.com/brightpuddle/clara/releases/download/v#{version}/clara_#{version}_darwin_amd64.tar.gz"
      sha256 "78cd8a8d964c23f1a55ba3f1d9ac86302c7d8e3f31034754ae125932037f3b66"
    end
    on_arm do
      url "https://github.com/brightpuddle/clara/releases/download/v#{version}/clara_#{version}_darwin_arm64.tar.gz"
      sha256 "9e772aae8c043f0a194af60e1994828963293646803178449666750afefc5d17"
    end
  end

  caveats do
    "To use the Chrome extension:"
    "1. Open Chrome -> chrome://extensions/"
    "2. Enable "Developer mode""
    "3. Click "Load unpacked""
    "4. Select: #{staged_path}/extension"
    ""
    "To start the Clara agent:"
    "1. Copy the launch agent to your user directory:"
    "   cp #{staged_path}/com.brightpuddle.clara.agent.plist ~/Library/LaunchAgents/"
    "2. Start it:"
    "   launchctl load ~/Library/LaunchAgents/com.brightpuddle.clara.agent.plist"
    ""
    "An example configuration is available at:"
    "#{staged_path}/config.yaml.example"
  end

  # No zap stanza required
end
